VIA_ENABLE = yes
VIAL_ENABLE = yes

EEPROM_DRIVER = wear_leveling
WEAR_LEVELING_DRIVER = rp2040_flash

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c

COMBO_ENABLE = yes

QMK_SETTINGS = yes
WPM_ENABLE = yes
